"""
Pytest configuration for the Lab04 test suite (23CSE301).

Both lab03.py and lab04.py read the Excel file with a relative path at module
level, and lab03.py is located in the sibling Lab03/ directory. This conftest
loads each module from its own directory (chdir before import, restore after)
and exposes the modules through session-scoped fixtures.

# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Write a
# conftest that loads lab03 and lab04 modules from their own directories so
# their relative Excel reads and plot saves work under pytest."
"""

import importlib.util
import os
import sys

import pytest

REPO = os.path.dirname(os.path.abspath(__file__))
LAB03_DIR = os.path.join(os.path.dirname(REPO), "Lab03")
LAB04_DIR = REPO


def _load_module(name, directory):
    """Load a module by absolute path from its own working directory."""
    cwd = os.getcwd()
    added = False
    try:
        os.chdir(directory)
        if directory not in sys.path:
            sys.path.insert(0, directory)
            added = True
        spec = importlib.util.spec_from_file_location(
            name, os.path.join(directory, name + ".py")
        )
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        if added:
            sys.path.remove(directory)
        os.chdir(cwd)


@pytest.fixture(scope="session")
def lab03():
    """The student's own Lab03 module (the hand-written version)."""
    return _load_module("lab03", LAB03_DIR)


@pytest.fixture(scope="session")
def lab04():
    """The AI-generated Lab04 module (the repeat of the Lab03 experiments)."""
    return _load_module("lab04", LAB04_DIR)
