"""
Lab Session 04 (23CSE301) - A1: Repeat of Lab03 experiments using AI tools.

The function definitions and the modularization are the student's own work
(they mirror Lab03/lab03.py exactly). The AI tool (DeepSeek-V4-Flash-0731
via custom pi harness) generated the code bodies.

Every AI-generated code portion carries a comment of the form:
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - <prompt summary>
"""

# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Set up the
# headless plotting backend and the imports for the AI repeat of Lab03."
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.spatial import distance as sd

# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Load the
# marketing_campaign sheet from Lab Session Data.xlsx at module level."
df = pd.read_excel("Lab Session Data.xlsx", sheet_name="marketing_campaign")


def a1():
    """Survey the feature types of the marketing_campaign dataset."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Print the
    # datatype and a crude categorical/numeric guess for every column."
    print("\nA1. feature types")
    for c in df.columns:
        n = df[c].nunique()
        t = "cat" if n < 20 else "num"
        print(c, df[c].dtype, n, t)


def label_encode(s):
    """Label-encode a categorical Series into integer codes."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Map each
    # distinct value to its first-seen integer index and return the code list."
    mp = {}
    res = []
    for v in s:
        if v not in mp:
            mp[v] = len(mp)
        res.append(mp[v])
    return res


def one_hot_encode(s):
    """One-hot encode a categorical Series into an indicator DataFrame."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Build a
    # DataFrame with one indicator column per distinct value of the Series."
    lev = []
    for v in s:
        if v not in lev:
            lev.append(v)
    rows = []
    for v in s:
        rows.append([1 if v == l else 0 for l in lev])
    return pd.DataFrame(rows, columns=["%s_%s" % (s.name, l) for l in lev])


def a2():
    """Demonstrate label encoding and one-hot encoding on two columns."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Show the
    # label mapping for Education and the one-hot columns for Marital_Status."
    print("\nA2. encoding")
    e = label_encode(df["Education"])
    print(dict(zip(df["Education"], e)))
    print(e[:5])
    o = one_hot_encode(df["Marital_Status"])
    print(list(o.columns))
    print(o.head())


def a3():
    """Build the fully encoded dataset and report the dimensionality change."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Ordinal
    # map Education, one-hot Marital_Status, add the customer year, and drop
    # the raw columns and the ID."
    print("\nA3. encoded dataset")
    d = df.copy()
    eord = ["Basic", "2n Cycle", "Graduation", "Master", "PhD"]
    em = {e: i for i, e in enumerate(eord)}
    d["Education"] = [em[v] for v in d["Education"]]
    o = one_hot_encode(d["Marital_Status"])
    for c in o.columns:
        d[c] = o[c].values
    d = d.drop(columns=["Marital_Status"])
    d["Year_Customer"] = [pd.to_datetime(t).year for t in d["Dt_Customer"]]
    d = d.drop(columns=["Dt_Customer", "ID"])
    print("before:", df.shape[1], "after:", d.shape[1])
    return d


def minkowski(x, y, p):
    """Compute the Minkowski distance of order p between two vectors."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Vectorize
    # the Minkowski sum with numpy: sum of |xi-yi|**p, then the p-th root."
    x = np.asarray(x, dtype=float)
    y = np.asarray(y, dtype=float)
    return float(np.sum(np.abs(x - y) ** p) ** (1.0 / p))


def a4():
    """Test the custom Minkowski function on a small vector pair."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Print the
    # Manhattan, Euclidean, and cubic distances for the given vectors."
    print("\nA4. custom minkowski")
    x = np.array([1, 2, 3])
    y = np.array([4, 6, 3])
    print(minkowski(x, y, 1), minkowski(x, y, 2), minkowski(x, y, 3))


def a5(enc):
    """Compute Minkowski distances for p from 1 to 10 and plot them."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Take the
    # first two numeric feature vectors, loop p from 1 to 10, and plot the
    # distances."
    print("\nA5. p from 1 to 10")
    num = enc.select_dtypes(include=np.number)
    x = num.iloc[0].to_numpy()
    y = num.iloc[1].to_numpy()
    ps = list(range(1, 11))
    ds = [minkowski(x, y, p) for p in ps]
    for p, dd in zip(ps, ds):
        print(p, round(dd, 4))
    plt.plot(ps, ds, marker="o")
    plt.xlabel("p")
    plt.ylabel("distance")
    plt.grid()
    plt.savefig("minkowski_plot.png")
    print("saved plot")
    return x, y, ps, ds


def a6(x, y, ps):
    """Compare the custom Minkowski function with scipy's implementation."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Compare
    # the custom distances with scipy.spatial.distance.minkowski for each p."
    print("\nA6. mine vs scipy")
    for p in ps:
        mine = minkowski(x, y, p)
        lib = sd.minkowski(x, y, p)
        print(p, round(mine, 6), round(lib, 6), abs(mine - lib))


def dot(a, b):
    """Compute the dot product of two vectors."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Return
    # the element-wise product sum, vectorized with numpy."
    a = np.asarray(a, dtype=float)
    b = np.asarray(b, dtype=float)
    return float(np.sum(a * b))


def euc_len(a):
    """Compute the Euclidean norm of a vector."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Return
    # the square root of the sum of squares, vectorized with numpy."
    a = np.asarray(a, dtype=float)
    return float(np.sqrt(np.sum(a * a)))


def a7():
    """Compare the custom dot and norm with numpy."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Print the
    # custom and numpy results for the dot product and the Euclidean norm."
    print("\nA7. dot and euclidean length")
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    print("dot:", dot(a, b), "numpy:", np.dot(a, b))
    print("len a:", euc_len(a), "numpy:", np.linalg.norm(a))
    print("len b:", euc_len(b), "numpy:", np.linalg.norm(b))


def mean(s):
    """Compute the mean of a set of values, ignoring NaN values."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Filter
    # NaN values and return the arithmetic mean."
    s = [v for v in s if v == v]
    return sum(s) / len(s)


def variance(s):
    """Compute the population variance of a set of values."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Return
    # the mean of the squared deviations from the mean. This matches the
    # student's Lab03 behavior exactly (no NaN filter inside variance)."
    mu = mean(s)
    res = 0
    for v in s:
        res += (v - mu) ** 2
    return res / len(s)


def std_dev(s):
    """Compute the population standard deviation of a set of values."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Return
    # the square root of the variance."
    return variance(s) ** 0.5


def a8():
    """Compute the mean income with the custom functions."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Print the
    # mean income computed with the custom mean function."
    print("\nA8. custom mean, variance, and std.deviation")
    a = mean(df["Income"])
    print(f"avg income: {a}")


def a9():
    """Compare the custom mean/std with numpy on three feature columns."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Compare
    # the custom column means and stds with numpy mean and std."
    print("\nA9. mine vs numpy on a few cols")
    cols = ["MntWines", "Recency", "MntMeatProducts"]
    x = df[cols].to_numpy()
    mm = [mean(x[:, i]) for i in range(x.shape[1])]
    ss = [std_dev(x[:, i]) for i in range(x.shape[1])]
    nm = x.mean(axis=0)
    ns = x.std(axis=0)
    for i, c in enumerate(cols):
        print(c, "mean", round(mm[i], 2), "vs", round(nm[i], 2), "| std", round(ss[i], 2), "vs", round(ns[i], 2))


def a10():
    """Plot and summarize the histogram of the MntWines feature."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Use
    # numpy.histogram with 10 bins, print the bucket counts, and save a
    # matplotlib histogram."
    print("\nA10. histogram of MntWines")
    f = df["MntWines"].to_numpy()
    cnt, bins = np.histogram(f, bins=10)
    for i in range(len(cnt)):
        print("%d-%d: %d" % (bins[i], bins[i + 1], cnt[i]))
    plt.hist(f, bins=10, edgecolor="black")
    plt.xlabel("MntWines")
    plt.ylabel("count")
    plt.grid()
    plt.savefig("hist_mntwines.png")
    print("mean:", round(mean(f), 2), "var:", round(variance(f), 2))


def kmeans(k, points):
    """
    Run the k-means algorithm.

    The initialization uses the first k points as centroids, exactly like the
    student's Lab03 version. The metric is Euclidean. The loop stops when no
    centroid changes.
    """
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Implement
    # k-means with numpy: first-k-point centroid init, vectorized assignment
    # to the nearest centroid, mean recomputation, loop until stable; return
    # the centroids, the labels, and the iteration count."
    pts = np.asarray(points, dtype=float)
    k = int(k)
    centroids = pts[:k].copy()
    labels = np.zeros(pts.shape[0], dtype=int)
    iterations = 0
    while True:
        iterations += 1
        old = centroids.copy()
        # Assignment step: distance from each point to each centroid.
        diffs = pts[:, None, :] - centroids[None, :, :]
        dists = np.sqrt(np.sum(diffs * diffs, axis=2))
        labels = np.argmin(dists, axis=1)
        # Update step: recompute each centroid as the cluster mean.
        new_centroids = np.zeros_like(centroids)
        for j in range(k):
            cluster = pts[labels == j]
            if len(cluster) > 0:
                new_centroids[j] = cluster.mean(axis=0)
            else:
                new_centroids[j] = old[j]
        centroids = new_centroids
        if np.array_equal(centroids, old):
            break
    return centroids.tolist(), labels.tolist(), iterations


def a11(k, points):
    """Run k-means on the given points and print the final centroids."""
    # Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Call the
    # kmeans function and print the final centroids, like Lab03 a11."
    centroids, labels, iterations = kmeans(k, points)
    print("Centroids: ", centroids)
    print("Iterations: ", iterations)


if __name__ == "__main__":
    print(df.shape)
    a1()
    a2()
    enc = a3()
    a4()
    x, y, ps, ds = a5(enc)
    a6(x, y, ps)
    a7()
    a8()
    a9()
    a10()
    points = [[0, 1], [1, 1], [2, 2], [3, 3], [-1, 1], [0, -1], [-1, -1]]
    a11(3, points)
