"""
Unit tests for the AI-generated Lab04 module (Lab04/lab04.py).

The tests target the same modular functions as the Lab03 suite, plus the
AI k-means function, which returns (centroids, labels, iterations).

# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Generate
# pytest unit tests for lab04.py covering correctness against hand-computed
# values and scipy/numpy references, plus the kmeans return contract."
"""

import numpy as np
import pandas as pd
import pytest
from scipy.spatial import distance as sd


def test_label_encode_first_seen_order(lab04):
    result = lab04.label_encode(["b", "a", "b", "c", "a"])
    assert result == [0, 1, 0, 2, 1]


def test_label_encode_unknown_values_get_new_codes(lab04):
    result = lab04.label_encode(["a", "b", "c", "d", "e"])
    assert result == [0, 1, 2, 3, 4]


def test_one_hot_encode_columns_and_values(lab04):
    s = pd.Series(["a", "b", "a"], name="X")
    ohe = lab04.one_hot_encode(s)
    assert list(ohe.columns) == ["X_a", "X_b"]
    assert ohe.to_numpy().tolist() == [[1, 0], [0, 1], [1, 0]]


def test_one_hot_encode_single_level(lab04):
    s = pd.Series(["z", "z"], name="Y")
    ohe = lab04.one_hot_encode(s)
    assert list(ohe.columns) == ["Y_z"]
    assert ohe.to_numpy().tolist() == [[1], [1]]


def test_minkowski_p1_manhattan(lab04):
    x = np.array([1, 2, 3])
    y = np.array([4, 6, 3])
    assert lab04.minkowski(x, y, 1) == pytest.approx(7.0)


def test_minkowski_p2_euclidean(lab04):
    x = np.array([1, 2, 3])
    y = np.array([4, 6, 3])
    assert lab04.minkowski(x, y, 2) == pytest.approx(5.0)


def test_minkowski_p3_hand_computed(lab04):
    x = np.array([1, 2, 3])
    y = np.array([4, 6, 3])
    expected = (3.0**3 + 4.0**3) ** (1.0 / 3.0)
    assert lab04.minkowski(x, y, 3) == pytest.approx(expected)


def test_minkowski_matches_scipy_random(lab04):
    rng = np.random.default_rng(7)
    x = rng.normal(size=8)
    y = rng.normal(size=8)
    for p in [1, 2, 4, 10]:
        assert lab04.minkowski(x, y, p) == pytest.approx(
            sd.minkowski(x, y, p), rel=1e-9
        )


def test_minkowski_identical_vectors_zero(lab04):
    x = np.array([1.0, -2.0, 3.5])
    assert lab04.minkowski(x, x, 4) == pytest.approx(0.0)


def test_dot_matches_numpy(lab04):
    rng = np.random.default_rng(3)
    a = rng.normal(size=5)
    b = rng.normal(size=5)
    assert lab04.dot(a, b) == pytest.approx(np.dot(a, b))


def test_dot_negative_components(lab04):
    assert lab04.dot([-1, 2, -3], [4, -5, 6]) == pytest.approx(-32.0)


def test_euc_len_matches_numpy(lab04):
    a = np.array([1.0, 2.0, 3.0, 4.0])
    assert lab04.euc_len(a) == pytest.approx(np.linalg.norm(a))


def test_euc_len_zero_vector(lab04):
    assert lab04.euc_len([0, 0, 0]) == pytest.approx(0.0)


def test_mean_matches_numpy(lab04):
    data = [2.0, 4.0, 6.0, 8.0]
    assert lab04.mean(data) == pytest.approx(np.mean(data))


def test_mean_ignores_nan(lab04):
    assert lab04.mean([1.0, 2.0, float("nan")]) == pytest.approx(1.5)


def test_variance_population_matches_numpy(lab04):
    data = [1.0, 2.0, 3.0, 4.0]
    assert lab04.variance(data) == pytest.approx(np.var(data))


def test_std_dev_matches_numpy(lab04):
    data = [1.0, 2.0, 3.0, 4.0]
    assert lab04.std_dev(data) == pytest.approx(np.std(data))


def test_variance_single_value_is_zero(lab04):
    assert lab04.variance([5.0]) == pytest.approx(0.0)


def test_kmeans_toy_centroids(lab04):
    points = [[0, 1], [1, 1], [2, 2], [3, 3], [-1, 1], [0, -1], [-1, -1]]
    centroids, labels, iterations = lab04.kmeans(3, points)
    assert centroids[0] == pytest.approx([-2.0 / 3.0, -1.0 / 3.0])
    assert centroids[1] == pytest.approx([0.5, 1.0])
    assert centroids[2] == pytest.approx([2.5, 2.5])


def test_kmeans_two_clusters(lab04):
    points = [[0, 0], [0, 1], [10, 0], [10, 1]]
    centroids, labels, iterations = lab04.kmeans(2, points)
    assert centroids[0] == pytest.approx([5.0, 0.0])
    assert centroids[1] == pytest.approx([5.0, 1.0])
    assert len(labels) == 4


def test_kmeans_deterministic(lab04):
    points = [[0, 1], [1, 1], [2, 2], [3, 3], [-1, 1], [0, -1], [-1, -1]]
    c1, _, _ = lab04.kmeans(3, points)
    c2, _, _ = lab04.kmeans(3, points)
    assert c1 == c2


def test_kmeans_iterations_at_least_one(lab04):
    points = [[0, 1], [1, 1], [2, 2], [3, 3], [-1, 1], [0, -1], [-1, -1]]
    _, _, iterations = lab04.kmeans(3, points)
    assert iterations >= 1


def test_kmeans_converges_on_random_blobs(lab04):
    rng = np.random.default_rng(11)
    blobs = []
    for _ in range(3):
        c = rng.normal(size=2) * 10
        blobs.append(rng.normal(loc=c, scale=1.0, size=(40, 2)))
    data = np.vstack(blobs)
    centroids, labels, iterations = lab04.kmeans(3, data)
    assert len(centroids) == 3
    assert len(labels) == len(data)
    assert iterations >= 1
