"""
Unit tests for the student's own Lab03 module (Lab03/lab03.py).

These tests target the hand-written modular functions from the previous lab:
label_encode, one_hot_encode, minkowski, dot, euc_len, mean, variance,
std_dev, and the k-means implementation in a11.

# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Generate
# pytest unit tests for lab03.py covering correctness against hand-computed
# values and scipy/numpy references, plus k-means output checks."
"""

import numpy as np
import pandas as pd
import pytest
from scipy.spatial import distance as sd


def test_label_encode_first_seen_order(lab03):
    result = lab03.label_encode(["b", "a", "b", "c", "a"])
    assert result == [0, 1, 0, 2, 1]


def test_label_encode_is_deterministic(lab03):
    s = ["x", "y", "x", "z"]
    assert lab03.label_encode(s) == lab03.label_encode(s)


def test_label_encode_on_education_column(lab03):
    codes = lab03.label_encode(lab03.df["Education"])
    assert len(codes) == len(lab03.df)
    assert len(set(codes)) == lab03.df["Education"].nunique()


def test_one_hot_encode_columns_and_values(lab03):
    s = pd.Series(["a", "b", "a"], name="X")
    ohe = lab03.one_hot_encode(s)
    assert list(ohe.columns) == ["X_a", "X_b"]
    assert ohe.to_numpy().tolist() == [[1, 0], [0, 1], [1, 0]]


def test_one_hot_encode_row_sums_to_one(lab03):
    s = pd.Series(["a", "b", "c", "a"], name="X")
    ohe = lab03.one_hot_encode(s)
    assert (ohe.sum(axis=1) == 1).all()


def test_one_hot_encode_column_counts(lab03):
    s = pd.Series(["a", "b", "a", "a", "b"], name="X")
    ohe = lab03.one_hot_encode(s)
    assert ohe["X_a"].sum() == 3
    assert ohe["X_b"].sum() == 2


def test_minkowski_p1_manhattan(lab03):
    x = np.array([1, 2, 3])
    y = np.array([4, 6, 3])
    assert lab03.minkowski(x, y, 1) == pytest.approx(7.0)


def test_minkowski_p2_euclidean(lab03):
    x = np.array([1, 2, 3])
    y = np.array([4, 6, 3])
    assert lab03.minkowski(x, y, 2) == pytest.approx(5.0)


def test_minkowski_identical_vectors_zero(lab03):
    x = np.array([3.5, -1.0, 7.2])
    assert lab03.minkowski(x, x, 5) == pytest.approx(0.0)


def test_minkowski_matches_scipy_random(lab03):
    rng = np.random.default_rng(42)
    x = rng.normal(size=6)
    y = rng.normal(size=6)
    for p in [1, 2, 3, 7]:
        assert lab03.minkowski(x, y, p) == pytest.approx(
            sd.minkowski(x, y, p), rel=1e-9
        )


def test_dot_matches_numpy(lab03):
    a = np.array([1, 2, 3])
    b = np.array([4, 5, 6])
    assert lab03.dot(a, b) == pytest.approx(np.dot(a, b))


def test_dot_hand_computed(lab03):
    assert lab03.dot([1, 2, 3], [4, 5, 6]) == pytest.approx(32.0)


def test_euc_len_matches_numpy(lab03):
    a = np.array([3, 4])
    assert lab03.euc_len(a) == pytest.approx(np.linalg.norm(a))


def test_euc_len_hand_computed(lab03):
    assert lab03.euc_len([3, 4]) == pytest.approx(5.0)


def test_mean_matches_numpy(lab03):
    data = [1.0, 2.0, 3.0, 4.0]
    assert lab03.mean(data) == pytest.approx(np.mean(data))


def test_mean_ignores_nan(lab03):
    assert lab03.mean([1.0, 2.0, float("nan")]) == pytest.approx(1.5)


def test_variance_population_matches_numpy(lab03):
    data = [1.0, 2.0, 3.0, 4.0]
    assert lab03.variance(data) == pytest.approx(np.var(data))


def test_std_dev_matches_numpy(lab03):
    data = [1.0, 2.0, 3.0, 4.0]
    assert lab03.std_dev(data) == pytest.approx(np.std(data))


def test_variance_hand_computed(lab03):
    assert lab03.variance([1, 2, 3, 4]) == pytest.approx(1.25)


def test_kmeans_toy_centroids(capsys, lab03):
    points = [[0, 1], [1, 1], [2, 2], [3, 3], [-1, 1], [0, -1], [-1, -1]]
    lab03.a11(3, points)
    captured = capsys.readouterr()
    assert "Centroids" in captured.out
    assert "[-0.6666666666666666, -0.3333333333333333]" in captured.out
    assert "[0.5, 1.0]" in captured.out
    assert "[2.5, 2.5]" in captured.out


def test_kmeans_toy_two_clusters(capsys, lab03):
    points = [[0, 0], [0, 1], [10, 0], [10, 1]]
    lab03.a11(2, points)
    captured = capsys.readouterr()
    assert "[5.0, 0.0]" in captured.out
    assert "[5.0, 1.0]" in captured.out


def test_kmeans_deterministic(capsys, lab03):
    points = [[0, 1], [1, 1], [2, 2], [3, 3], [-1, 1], [0, -1], [-1, -1]]
    lab03.a11(3, points)
    first = capsys.readouterr().out
    lab03.a11(3, points)
    second = capsys.readouterr().out
    assert first == second
