"""
Pytest configuration for the Lab06 test suite (23CSE301).

`lab06.py` and `lab5.py` read the Excel file with a relative path, and lab5.py
sits in the sibling Lab05/ directory. This conftest loads each module from its
own directory (chdir before import, restore after) and registers lab5 in
sys.modules so that lab06's `import lab5` reuses the same instance.

# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Write a
# conftest that loads lab5 (Lab05) and lab06 (Lab06) from their own
# directories so their relative Excel reads work under pytest, and reuse the
# lab5 instance when lab06 imports it."
"""

import importlib.util
import os
import sys

import pytest

REPO = os.path.dirname(os.path.abspath(__file__))
LAB05_DIR = os.path.join(os.path.dirname(REPO), "Lab05")
LAB06_DIR = REPO


def _load_module(name, directory):
    """Load a module by absolute path from its own working directory."""
    cwd = os.getcwd()
    added = False
    try:
        os.chdir(directory)
        if directory not in sys.path:
            sys.path.insert(0, directory)
            added = True
        spec = importlib.util.spec_from_file_location(
            name, os.path.join(directory, name + ".py")
        )
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module
    finally:
        if added:
            sys.path.remove(directory)
        os.chdir(cwd)


@pytest.fixture(scope="session")
def lab5():
    """The student's modular k-NN code from Lab 05 (last week's exercise)."""
    return _load_module("lab5", LAB05_DIR)


@pytest.fixture(scope="session")
def lab06(lab5):
    """The AI-assisted Lab06 module (the repeat of the Lab 05 experiments).

    Depends on `lab5` so the already-loaded instance is reused when lab06.py
    runs `import lab5`.
    """
    return _load_module("lab06", LAB06_DIR)
