"""
23CSE301 - Lab Session 06 (AI-tool repeat of Lab 05 k-NN experiments).

The function definitions and the code modularization are the student's own
work. The code bodies for each section below were generated by
DeepSeek-V4-Flash-0731 (via custom pi harness). The GenAI tool used for each
portion is noted as a comment on that portion, as required by A1.

A3 requirement: this script also compares three k-NN versions (own code,
scikit-learn, GenAI code) on accuracy, precision, recall, F-score and average
wall time of 10 runs. Results are written to benchmark_lab06_results.csv.
"""

import os
import sys
import time

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

# Reuse the modular k-NN building blocks written for Lab 05 (student code).
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "Lab05"))
import lab5

df = pd.read_excel("Lab Session Data.xlsx", sheet_name="marketing_campaign")


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "prepare the features from the Lab05 encode/impute functions"
def prepare():
    encoded = lab5.encode(df)
    imputed = lab5.impute(encoded, "mean")
    X = imputed.drop(columns=["Response"]).to_numpy(dtype=float)
    y = imputed["Response"].to_numpy()
    return X, y


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A1: encoding and imputation repeat from Lab05"
def a1():
    print("\nA1. encoding and imputation")
    encoded = lab5.encode(df)
    print("raw columns:", df.shape[1], "encoded columns:", encoded.shape[1])
    print("all numeric after encoding:", encoded.select_dtypes(include="number").shape[1] == encoded.shape[1])
    print("missing before imputation:", int(encoded["Income"].isna().sum()))
    for strategy in ("mean", "median", "mode"):
        filled = lab5.impute(encoded, strategy)
        print("strategy=%-6s missing after: %d" % (strategy, int(filled["Income"].isna().sum())))


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A2: distance, sorting, neighbors, voting checks"
def a2():
    print("\nA2. distance, sorting, neighbors, voting")
    x = np.array([1.0, 2.0, 3.0])
    y = np.array([4.0, 6.0, 3.0])
    print("euclidean       :", round(lab5.distance(x, y, "euclidean"), 4))
    print("manhattan       :", round(lab5.distance(x, y, "manhattan"), 4))
    print("minkowski p = 3 :", round(lab5.distance(x, y, "minkowski", p=3), 4))
    pairs = [(3.5, 0), (1.2, 1), (2.7, 2), (1.2, 3), (0.9, 4)]
    for algo in ("insertion", "merge", "quick", "heap"):
        print("sort_algo=%-9s -> %s" % (algo, lab5.sort_by_distance([d for d, _ in pairs], algo)))
    tie_distances = [1.0, 2.0, 2.0, 2.0, 5.0]
    print("neighbors k=2 with ties:", lab5.find_neighbors(tie_distances, 2, "merge"))
    tie_labels = ["A", "B", "A", "B"]
    tie_order = [1.0, 2.0, 3.0, 4.0]
    print("majority vote  :", lab5.majority_vote(tie_labels, tie_order))
    print("weighted vote  :", lab5.weighted_majority_vote(tie_labels, tie_order))


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A3: sklearn train-test split"
def a3(X, y):
    print("\nA3. train-test split (sklearn)")
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
    print("train:", X_train.shape, "test:", X_test.shape)
    print("train class counts:", np.unique(y_train, return_counts=True))
    print("test class counts :", np.unique(y_test, return_counts=True))
    return X_train, X_test, y_train, y_test


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A4: fit an sklearn kNN with k=3"
def a4(X_train, y_train):
    print("\nA4. sklearn kNN k=3")
    neigh = KNeighborsClassifier(n_neighbors=3)
    neigh.fit(X_train, y_train)
    print("fitted on %d patterns" % len(X_train))
    return neigh


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A5: test accuracy"
def a5(neigh, X_test, y_test):
    print("\nA5. test accuracy")
    print("score:", round(neigh.score(X_test, y_test), 4))


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A6: predict behaviour on the test set"
def a6(neigh, X_test, y_test):
    print("\nA6. predict behavior")
    preds = neigh.predict(X_test)
    print("first 10 predictions:", preds[:10].tolist())
    print("first 10 actuals    :", y_test[:10].tolist())
    print("matches:", int((preds == y_test).sum()), "of", len(y_test))
    print("predicted class counts:", np.unique(preds, return_counts=True))


# Function/class definition written by the student; the body was generated by
# DeepSeek-V4-Flash-0731 (via custom pi harness) - "wrap lab5.classify in a
# Fit/Predict/Score style class like sklearn"
class KNN:
    def __init__(self, k=3, metric="euclidean", weighted=False, sort_algo="merge"):
        self.k = k
        self.metric = metric
        self.weighted = weighted
        self.sort_algo = sort_algo

    def fit(self, X_train, y_train):
        self.X_train = np.asarray(X_train, dtype=float)
        self.y_train = np.asarray(y_train)
        return self

    def predict(self, X_test):
        return lab5.classify(self.X_train, self.y_train, X_test, k=self.k,
                             metric=self.metric, weighted=self.weighted,
                             sort_algo=self.sort_algo)

    def score(self, X_test, y_test):
        return lab5.accuracy(np.asarray(y_test), self.predict(X_test))


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A7: run own Fit/Predict/Score"
def a7(X_train, X_test, y_train, y_test):
    print("\nA7. own Fit/Predict/Score")
    knn = KNN(k=3).fit(X_train, y_train)
    preds = knn.predict(X_test)
    print("first 10 predictions:", preds[:10])
    print("score:", round(knn.score(X_test, y_test), 4))
    return knn


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A8: accuracy of own vs sklearn kNN over several k, with plot"
def a8(X_train, X_test, y_train, y_test):
    print("\nA8. mine vs sklearn over k")
    ks = list(range(1, 16, 2))
    mine = []
    lib = []
    for k in ks:
        m = KNN(k=k).fit(X_train, y_train).score(X_test, y_test)
        s = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train).score(X_test, y_test)
        mine.append(m)
        lib.append(s)
        print("k=%2d mine=%.4f sklearn=%.4f" % (k, m, s))
    plt.plot(ks, mine, marker="o", label="mine")
    plt.plot(ks, lib, marker="s", label="sklearn")
    plt.xlabel("k")
    plt.ylabel("accuracy")
    plt.legend()
    plt.grid()
    plt.savefig("knn_compare.png")
    print("saved knn_compare.png")
    return ks, mine, lib


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A9: weighted kNN vs the unweighted baseline, with plot"
def a9(X_train, X_test, y_train, y_test, ks, mine, lib):
    print("\nA9. weighted kNN vs A8")
    mine_w = []
    lib_w = []
    for k in ks:
        m = KNN(k=k, weighted=True).fit(X_train, y_train).score(X_test, y_test)
        s = KNeighborsClassifier(n_neighbors=k, weights="distance").fit(X_train, y_train).score(X_test, y_test)
        mine_w.append(m)
        lib_w.append(s)
        print("k=%2d mine=%.4f sklearn=%.4f" % (k, m, s))
    plt.plot(ks, mine, marker="o", label="mine unweighted (A8)")
    plt.plot(ks, mine_w, marker="^", label="mine weighted")
    plt.plot(ks, lib_w, marker="s", label="sklearn weighted")
    plt.xlabel("k")
    plt.ylabel("accuracy")
    plt.legend()
    plt.grid()
    plt.savefig("knn_weighted_compare.png")
    print("saved knn_weighted_compare.png")


# Function definition by the student; body generated by DeepSeek-V4-Flash-0731
# (via custom pi harness) - "vectorize k-NN with numpy broadcasting and
# per-batch argsort, tie-break with stable sort"
def genai_knn(X_train, y_train, X_test, k=3, chunk=64):
    X_train = np.asarray(X_train, dtype=float)
    X_test = np.asarray(X_test, dtype=float)
    y_train = np.asarray(y_train)
    preds = []
    for start in range(0, len(X_test), chunk):
        batch = X_test[start:start + chunk]
        dists = ((batch[:, None, :] - X_train[None, :, :]) ** 2).sum(axis=2)
        order = np.argsort(dists, axis=1, kind="stable")[:, :k]
        labels = y_train[order]
        for row in labels:
            counts = np.bincount(row)
            preds.append(counts.argmax())
    return np.asarray(preds)


# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) -
# "A3: benchmark three k-NN versions - accuracy, precision, recall, f1 and
# average wall time of 10 runs; tabulate to CSV and plot"
def a10(X_train, X_test, y_train, y_test):
    print("\nA10. performance comparison of 3 k-NN versions")
    versions = {
        "mine": lambda: KNN(k=3).fit(X_train, y_train).predict(X_test),
        "sklearn": lambda: KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train).predict(X_test),
        "genai": lambda: genai_knn(X_train, y_train, X_test, k=3),
    }
    rows = []
    for name, fn in versions.items():
        preds = fn()
        acc = accuracy_score(y_test, preds)
        prec = precision_score(y_test, preds)
        rec = recall_score(y_test, preds)
        f1 = f1_score(y_test, preds)
        times = []
        for _ in range(10):
            t0 = time.perf_counter()
            fn()
            times.append(time.perf_counter() - t0)
        avg_time = sum(times) / len(times)
        rows.append([name, round(acc, 4), round(prec, 4), round(rec, 4), round(f1, 4), round(avg_time, 4)])
        print("%-8s acc=%.4f prec=%.4f rec=%.4f f1=%.4f time=%.4fs" % (name, acc, prec, rec, f1, avg_time))
    table = pd.DataFrame(rows, columns=["version", "accuracy", "precision", "recall", "f1", "avg_time"])
    table.to_csv("benchmark_lab06_results.csv", index=False)
    print("saved benchmark_lab06_results.csv")
    plt.figure(figsize=(10, 4))
    plt.subplot(1, 2, 1)
    metrics = ["accuracy", "precision", "recall", "f1"]
    x = np.arange(len(metrics))
    width = 0.25
    for i, name in enumerate(versions):
        plt.bar(x + i * width, [rows[i][j + 1] for j in range(4)], width, label=name)
    plt.xticks(x + width, metrics)
    plt.ylabel("score")
    plt.legend()
    plt.grid(axis="y")
    plt.subplot(1, 2, 2)
    plt.bar([r[0] for r in rows], [r[5] for r in rows])
    plt.ylabel("avg time (s)")
    plt.yscale("log")
    plt.grid(axis="y")
    plt.tight_layout()
    plt.savefig("benchmark_lab06.png")
    print("saved benchmark_lab06.png")


if __name__ == "__main__":
    print(df.shape)
    a1()
    a2()
    X, y = prepare()
    X_train, X_test, y_train, y_test = a3(X, y)
    neigh = a4(X_train, y_train)
    a5(neigh, X_test, y_test)
    a6(neigh, X_test, y_test)
    a7(X_train, X_test, y_train, y_test)
    ks, mine, lib = a8(X_train, X_test, y_train, y_test)
    a9(X_train, X_test, y_train, y_test, ks, mine, lib)
    a10(X_train, X_test, y_train, y_test)
