"""
Unit tests for the Lab06 module (23CSE301).

A2 requires unit tests for both last week's and today's lab exercises.

- Last week (Lab 05): the modular building blocks in `lab5` (label/one-hot
  encoding, imputation, Minkowski distance, sorting, neighbor selection,
  majority/weighted voting, and the full k-NN classifier).
- Today (Lab 06): the AI-assisted Lab06 code — `prepare`, the Fit/Predict/
  Score `KNN` wrapper, and the GenAI vectorized `genai_knn`, cross-checked
  against scikit-learn.

# Generated by DeepSeek-V4-Flash-0731 (via custom pi harness) - "Generate
# pytest unit tests for Lab06 that cover the Lab05 modular functions and the
# Lab06 KNN wrapper / genai_knn, validating against hand-computed values and
# scikit-learn on a subset of the project data."
"""

import numpy as np
import pandas as pd
import pytest
from scipy.spatial import distance as sd
from sklearn.neighbors import KNeighborsClassifier

# --- fixtures: shared, labelled project-data subset --------------------------


def _split(X, y):
    from sklearn.model_selection import train_test_split
    return train_test_split(X, y, test_size=0.3, random_state=42)


@pytest.fixture(scope="module")
def subset(lab06):
    """A small labelled train/test subset extracted from the project data."""
    X, y = lab06.prepare()
    X_train, X_test, y_train, y_test = _split(X, y)
    return X_train[:300], X_test[:80], y_train[:300], y_test[:80]


@pytest.fixture(scope="module")
def encoded(lab06, lab5):
    """Encoded (not yet imputed) project data from last week's lab5 code."""
    return lab5.encode(lab06.df)


# --- last week (Lab 05): modular k-NN building blocks -----------------------


def test_label_encode_first_seen_order(lab5):
    assert lab5.label_encode(["b", "a", "b", "c", "a"]) == [0, 1, 0, 2, 1]


def test_one_hot_encode_columns_and_values(lab5):
    s = pd.Series(["a", "b", "a"], name="X")
    ohe = lab5.one_hot_encode(s)
    assert list(ohe.columns) == ["X_a", "X_b"]
    assert ohe.to_numpy().tolist() == [[1, 0], [0, 1], [1, 0]]


def test_encode_produces_only_numeric_columns(lab5, encoded):
    assert encoded.select_dtypes(include="number").shape[1] == encoded.shape[1]
    assert "Marital_Status" not in encoded.columns


def test_impute_all_strategies_fill_income(lab5, encoded):
    for strategy in ("mean", "median", "mode"):
        assert lab5.impute(encoded, strategy)["Income"].isna().sum() == 0


def test_impute_mean_matches_pandas(lab5):
    df = pd.DataFrame({"A": [1.0, 2.0, np.nan, 4.0], "B": [5.0, np.nan, 7.0, 8.0]})
    result = lab5.impute(df, "mean")
    expected = df.fillna(df.mean())
    assert np.allclose(result.to_numpy(dtype=float), expected.to_numpy(dtype=float))


def test_distance_metrics_hand_computed(lab5):
    x = np.array([1.0, 2.0, 3.0])
    y = np.array([4.0, 6.0, 3.0])
    assert lab5.distance(x, y, "euclidean") == pytest.approx(5.0)
    assert lab5.distance(x, y, "manhattan") == pytest.approx(7.0)
    expected = (3.0**3 + 4.0**3) ** (1.0 / 3.0)
    assert lab5.distance(x, y, "minkowski", p=3) == pytest.approx(expected)


def test_distance_matches_scipy_random(lab5):
    rng = np.random.default_rng(7)
    x = rng.normal(size=8)
    y = rng.normal(size=8)
    for p in (1, 2, 4, 10):
        assert lab5.minkowski(x, y, p) == pytest.approx(sd.minkowski(x, y, p), rel=1e-9)


@pytest.mark.parametrize("algo", ["insertion", "merge", "quick", "heap"])
def test_sort_algorithms_match_sorted(lab5, algo):
    rng = np.random.default_rng(42)
    values = rng.integers(0, 20, size=60).tolist()
    assert lab5.SORT_ALGORITHMS[algo](values) == sorted(values)


def test_sort_by_distance_orders_pairs(lab5):
    distances = [3.5, 1.2, 2.7, 1.2, 0.9]
    assert lab5.sort_by_distance(distances, "merge") == [(0.9, 4), (1.2, 1), (1.2, 3), (2.7, 2), (3.5, 0)]


def test_find_neighbors_keeps_all_ties_at_boundary(lab5):
    assert lab5.find_neighbors([1.0, 2.0, 2.0, 2.0, 5.0], 2) == [0, 1, 2, 3]


def test_voting_tie_and_weighted(lab5):
    labels = ["B", "A", "A", "B", "A", "B"]
    distances = [1.0, 1.05, 1.1, 1.15, 1.2, 1.25]
    assert lab5.majority_vote(labels, distances) == "B"
    assert lab5.weighted_majority_vote(labels, distances) == "A"


def test_full_classifier_matches_sklearn(lab5, subset):
    X_train, X_test, y_train, _ = subset
    mine = lab5.classify(X_train, y_train, X_test, k=3, sort_algo="merge")
    ref = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train).predict(X_test)
    assert mine == ref.tolist()


# --- today (Lab 06): prepare, KNN wrapper, genai_knn -------------------------


def test_prepare_returns_clean_float_matrix(lab06):
    X, y = lab06.prepare()
    assert X.shape[0] == y.shape[0]
    assert X.shape[1] > 1
    assert X.dtype == np.float64
    assert not np.isnan(X).any()
    assert y.dtype != np.float64


def test_knn_score_above_baseline(lab06, subset):
    X_train, X_test, y_train, y_test = subset
    knn = lab06.KNN(k=3).fit(X_train, y_train)
    assert knn.score(X_test, y_test) > 0.75


@pytest.mark.parametrize("k", [1, 3, 5])
def test_knn_matches_sklearn(lab06, subset, k):
    X_train, X_test, y_train, _ = subset
    mine = lab06.KNN(k=k).fit(X_train, y_train).predict(X_test)
    ref = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train).predict(X_test)
    assert mine == ref.tolist()


@pytest.mark.parametrize("k", [1, 3, 5])
def test_weighted_knn_matches_sklearn_distance(lab06, subset, k):
    X_train, X_test, y_train, _ = subset
    mine = lab06.KNN(k=k, weighted=True).fit(X_train, y_train).predict(X_test)
    ref = KNeighborsClassifier(n_neighbors=k, weights="distance").fit(X_train, y_train).predict(X_test)
    assert mine == ref.tolist()


@pytest.mark.parametrize("k", [1, 3, 5])
def test_genai_knn_matches_sklearn(lab06, subset, k):
    X_train, X_test, y_train, _ = subset
    genai = lab06.genai_knn(X_train, y_train, X_test, k=k)
    ref = KNeighborsClassifier(n_neighbors=k).fit(X_train, y_train).predict(X_test)
    assert genai.tolist() == ref.tolist()


def test_three_versions_agree_on_accuracy(lab06, subset):
    X_train, X_test, y_train, y_test = subset
    mine = lab06.KNN(k=3).fit(X_train, y_train).score(X_test, y_test)
    sk = KNeighborsClassifier(n_neighbors=3).fit(X_train, y_train).score(X_test, y_test)
    genai = lab06.accuracy_score(y_test, lab06.genai_knn(X_train, y_train, X_test, k=3))
    assert mine == pytest.approx(sk)
    assert genai == pytest.approx(sk)


def test_genai_knn_handles_chunk_boundaries(lab06, subset):
    # 80 test rows with a chunk size of 30 exercises the partial-last-chunk path.
    X_train, X_test, y_train, _ = subset
    ref = lab06.genai_knn(X_train, y_train, X_test, k=3, chunk=64)
    out = lab06.genai_knn(X_train, y_train, X_test, k=3, chunk=30)
    assert out.tolist() == ref.tolist()


def test_knn_empty_train_returns_same_length(lab06):
    # Degenerate but deterministic contract: predict length equals X_test length.
    knn = lab06.KNN(k=3).fit(np.zeros((3, 2)), np.array([0, 1, 0]))
    preds = knn.predict(np.array([[0.5, 0.5], [1.0, 1.0]]))
    assert len(preds) == 2
